name: CI - Ember Flight Icons
    
on:
  push:
    branches:
      - main
  pull_request: {}

env:
  NODE_VERSION: '16.x'

concurrency:
   group: ci-ember-flight-icons-${{ github.head_ref || github.ref }}
   cancel-in-progress: true

jobs:
  test:
    name: "Tests"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
        working-directory: packages/ember-flight-icons
      - name: Run Tests
        run: npm run test:ember:percy
        working-directory: packages/ember-flight-icons
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN_FLIGHT_EMBER_ICONS }}

  floating:
    name: "Floating Dependencies"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - name: Install Dependencies
        run: npm install --no-shrinkwrap
      - name: Run Tests
        run: npm run test:ember:percy
        working-directory: packages/ember-flight-icons
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN_FLIGHT_EMBER_ICONS }}

  try-scenarios:
    name: ${{ matrix.try-scenario }}
    runs-on: ubuntu-latest
    needs: 'test'

    strategy:
      fail-fast: false
      matrix:
        try-scenario:
          - ember-lts-3.24
          - ember-lts-3.28
          - ember-release
          - ember-beta
         # - ember-canary
          - ember-classic
          - embroider-safe
        # - embroider-optimized

    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        working-directory: packages/ember-flight-icons
        run: npm run test:ember:try ${{ matrix.try-scenario }}
        env:
          PERCY_ENABLE: 0 