name: CI - Flight Website

on:
  push:
    branches:
      - main
  pull_request: {}

env:
  NODE_VERSION: '16.x'

concurrency:
   group: ci-flight-website-${{ github.head_ref || github.ref }}
   cancel-in-progress: true

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
        working-directory: packages/flight-website

  test:
    name: "Test"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm run test:ember:percy
        working-directory: packages/flight-website
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN_WEBSITE }}
